# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_name', models.CharField(max_length=250)),
                ('field1', models.CharField(max_length=250)),
                ('field2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=250)),
                ('field1', models.CharField(max_length=250)),
                ('field2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motaje_name', models.CharField(max_length=250)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.Conjunto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_name', models.CharField(max_length=250)),
                ('field1', models.CharField(max_length=250)),
                ('field2', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='montaje',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.Plano'),
        ),
    ]
